# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4f1371b1b5e6c8840c6a18acfc1762c4507e248dcfbf21cb13305a8bdfd67304a4081ff3784b5b22030acf03de2b3fce1181816c0273ed876574dfa45712c47

test:
  secret_key_base: ffcfce2c9ea46ec0ead02b2c3e1eb5831ba5ca9657b95287391250b004283a2ee5da28fb5edc252689ac513ac42e46186f4ed8884616a771fdc71b4ebd6e00b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
